### ISSUE TITLE
Can SiamMOT be used for person search ?

### ISSUE THREAD

**Issue by thunanguyen** [amazon-research/siam-mot#1]
Hi, can I ask if SiamMOT can be used for person search because some of the other works like FairMOT have a Re-ID branch but SiamMOT seems to not have that?

**Comment by bingshuai2019** [comment]
Yes, current SiamMOT does not have a re-id branch to extract an instance-aware embedding that can be used for person search or person re-identification. However, it should be quite straightforward to add a separate re-id branch as our earlier technique report shows (https://arxiv.org/abs/2004.07786). Like FairMOT / JDE, you can train it with cross-entropy loss rather than triplet-based loss.
