### ISSUE TITLE
Flush the track memory for different videos.

### ISSUE THREAD

**Issue by bo-miao** [amazon-research/siam-mot#13]
Hi,

I noticed that "reset_siammot_status" or "flush_memory" are the modules to clear the memory between training on different videos, and they are not used in the training process.

However, I have frames from different videos in the training set. In that case, may I know how to refresh the memory after training on one video and then switch to another video?

Many thanks in advance.

**Comment by bingshuai2019** [comment]
Hi, 

"reset_siammot_status" is only needed during inference. This is needed because we should clear up all cached features and trajectory identity management when we start with a new video.

However, we don't need to care about this during training. The training pipeline will sample frames from different video, and will take care of the tracking model training. You should be able to find such details in the paper.

I'm happy to chat more if you need further clarification.
