### ISSUE TITLE
why need video in demos/demo_vis？

### ISSUE THREAD

**Issue by Lin1225** [amazon-research/siam-mot#3]
Hi everyone, I am new to learning cv and deep learning, and I use colab as my machine. My input video is person_car.mp4, and the output video should be in demos/demo_vis, but when I run demo.py, it needs person_car.mp4 in demos/demo_vis too, that is strange. Can somebody explain?
![image](https://user-images.githubusercontent.com/31918775/119918948-f5d2c880-bf9b-11eb-94c5-157b7539b47c.png)
this is my github  which store my [colab file](https://github.com/Lin1225/siam_mot_github)

**Comment by bingshuai2019** [comment]
This happens because of these lines: https://github.com/amazon-research/siam-mot/blob/main/demos/utils/vis_writer.py#L52-L53

The video writer writes down a large temporary file yo demos/demo_vis/person_car.mp4 (tracking outputs have been rendered to original video), then it is replaced with the compressed video.  If the demo runs through correctly, the file with the path demos/demo_vis/person_car.mp4  would be automatically generated. You should check whether the codes run it correctly.

If you have issue generating videos, you can try to use the setting --dump-video False, it will dump every frame of the video.

**Comment by usbhub** [comment]
You might want to try the suggestion here: https://github.com/amazon-research/siam-mot/issues/4#issuecomment-850837067 , could be related to the codec used by opencv causing a video to not be created

**Comment by Lin1225** [comment]
I will try it, thank you!

**Comment by dyh-bupt** [comment]
same problem.
how did you fix it, please?
