### ISSUE TITLE
how to output the video ?

### ISSUE THREAD

**Issue by TommyTang930** [amazon-research/siam-mot#4]
Thank you for your sharing.
I follow the README.md instruction. when I input the following command, like this:
python3 demos/demo.py --demo-video  test.mp4 --track-class person --dump-video True

I can't see any generated result video in the file "demos/demos_vis/". 

I have tried many commands, like these :

① 
python3 demos/demo.py --demo-video  test.mp4 --track-class person --dump-video True --output-path demos/demos_vis

② 
python3 demos/demo.py --demo-video  test.mp4 --track-class person --dump-video False 

③ 
python3 demos/demo.py --demo-video  test.mp4 --track-class person --dump-video False
--output-path demos/demos_vis

and so on.

any suggestions for it ? How to output the result video ? Thank you

**Comment by cr7legend** [comment]
Inside demos/utils/vis_writer.py change the arguments of cv2.VideoWriter_fourcc to mp4v like this 
    def _init_video_writer(self, frame_width, frame_height):
        self._video_path = os.path.join(self._output_path, self._file_name)
        self._video_writer = cv2.VideoWriter(str(self._video_path), cv2.VideoWriter_fourcc(*'mp4v'), self._fps,
                                            (int(frame_width), int(frame_height)))

**Comment by usbhub** [comment]
Thanks for the tip about the opencv fourcc. Was there any error indicating this or did it just not write anything? Also when you set --dumo-video to False did it not output any images to the demo_vis folder? What versions of opencv and ffmpeg are you using so that we can look into reproducing this?

**Comment by TommyTang930** [comment]
@usbhub 

the installed packages version invoked many errors. I succeed once. But now, the version caused other errors. it is annoying.

**Comment by usbhub** [comment]
It's hard to say anything without knowing details. What platform are you on (ubuntu 18/20 etc, aws or some other platform), are you using conda or a virtual environment, what is the output of `pip3 freeze` , what are the exact errors you are getting.

**Comment by cr7legend** [comment]
@usbhub the error when avc1 was passed as an argument to cv2.VideoWriter_fourcc(*'avc1') was this. The Error is difficult to catch since there isn't any red color ;)

[ERROR:0] global /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2650) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0] global /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2722) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter 

Since the VideoWriter wasn't initialized bounding boxes weren't written onto the video. When the dump video was false, no images were generated either. All of this was solved for me by the modification I had already mentioned.

I am using ubuntu 2004 and a conda environment with the following packages where you can find the versions of opencv and ffmpeg to be 4.5.2.52 and 0.2.0 respectively

The output of pip freeze

absl-py==0.12.0
apex==0.1
appdirs==1.4.4
attrs==21.2.0
autocfg==0.0.8
autogluon.core==0.2.0
autograd==1.3
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bcrypt==3.2.0
boto3==1.17.83
botocore==1.20.83
cachetools==4.2.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cityscapesScripts==2.2.0
click==8.0.1
cloudpickle==1.6.0
coloredlogs==15.0
ConfigSpace==0.4.18
cryptography==3.4.7
cycler==0.10.0
Cython==0.29.23
dask==2021.5.0
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
decord==0.5.2
dill==0.3.3
distributed==2021.5.0
ffmpeg-python==0.2.0
fire==0.4.0
flake8==3.9.2
flake8-import-order==0.18.1
fsspec==2021.5.0
future==0.18.2
gluoncv==0.10.1.post0
google-auth==1.30.1
google-auth-oauthlib==0.4.4
graphviz==0.8.4
grpcio==1.38.0
HeapDict==1.0.1
humanfriendly==9.1
idna==2.10
imageio==2.9.0
imgaug==0.4.0
importlib-metadata==4.3.0
indexed==1.2.1
iniconfig==1.1.1
ipython @ file:///tmp/build/80754af9/ipython_1617118429768/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
jedi==0.17.0
jmespath==0.10.0
joblib==1.0.1
kiwisolver==1.3.1
locket==0.2.1
Markdown==3.3.4
-e git+https://github.com/facebookresearch/maskrcnn-benchmark.git@57eec25b75144d9fb1a6857f32553e1574177daf#egg=maskrcnn_benchmark&subdirectory=../../maskrcnn-benchmark
matplotlib==3.4.2
mccabe==0.6.1
motmetrics==1.2.0
msgpack==1.0.2
mxnet==1.8.0.post0
networkx==2.5.1
ninja==1.10.0.post2
numpy==1.20.1
oauthlib==3.1.0
opencv-python==4.5.2.52
packaging==20.9
pandas==1.2.4
paramiko==2.7.2
parso @ file:///tmp/build/80754af9/parso_1617223946239/work
partd==1.2.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.2.0
pluggy==0.13.1
portalocker==2.3.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1616415428029/work
protobuf==3.17.1
psutil==5.8.0
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py==1.10.0
py-cpuinfo==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.2
pycodestyle==2.7.0
pycparser==2.20
pyflakes==2.3.1
Pygments @ file:///tmp/build/80754af9/pygments_1621606182707/work
PyNaCl==1.4.0
pyparsing==2.4.7
pyquaternion==0.9.9
pytest==6.2.4
pytest-benchmark==3.4.1
python-dateutil==2.8.1
pytz==2021.1
PyWavelets==1.1.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
s3transfer==0.4.2
scikit-image==0.18.1
scikit-learn==0.24.2
scipy==1.6.3
Shapely==1.7.1
six==1.16.0
sortedcontainers==2.4.0
tblib==1.7.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.2
termcolor==1.1.0
threadpoolctl==2.1.0
tifffile==2021.4.8
timm==0.4.9
toml==0.10.2
toolz==0.11.1
torch==1.7.1+cu110
torchvision==0.8.2+cu110
tornado==6.1
tqdm==4.61.0
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typing==3.10.0.0
typing-extensions==3.10.0.0
urllib3==1.26.5
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
Werkzeug==2.0.1
xmltodict==0.12.0
yacs==0.1.8
zict==2.0.0
zipp==3.4.1

**Comment by dyh-bupt** [comment]
Thank you, it works!
