### ISSUE TITLE
Logic behind padding features

### ISSUE THREAD

**Issue by cr7legend** [amazon-research/siam-mot#8]
Can I get the reasoning behind padding the features with zeros when using poolers to extract features for search regions(sr)? Also, why isn't padding done while pooling for proposals/detections? Any intuition behind the padding value chosen?

Code references:

In track_core.py EMM forward function:

            features = self.track_utils.pad_feature(features)
            sr_features = self.feature_extractor(features, boxes, sr)

Also, need an explanation for the following lines of code in track_utils.py in extend_bbox function. Shouldn't it be only the factor 2 instead of  (self.search_expansion * 2.)

            # todo: need to check the equation later
            min_w_ext = (self.min_search_wh - bbox_w) / (self.search_expansion * 2.)
            min_h_ext = (self.min_search_wh - bbox_h) / (self.search_expansion * 2.)

**Comment by bingshuai2019** [comment]
1. We assume that the proposal / detections are within image boundary so we don't need to pad features for them. This is usually the case of two-stage detection network. However, a search region is extended based on a detection, it's very likely that it covers image region outside image boundary. If its feature is not properly padded, then it only actually pools the features from a smaller image region, resulting a scale mismatch between the detection and its search region (in EMM, we expect that the search region is r \times of tracked detection, so its feature should also pool from r \times of the image region of detection). Otherwise, this may have an adversarial effect for object instances in the boundary.

2. You are right, that seems an earlier implementation bug if self.min_search_wh > 0. As we use self.min_search_wh = 0 throughout our experiments, this should not have an negative effect to the model performance. Thanks for pointing it out, we will fix it later.
