### ISSUE TITLE
Class imbalance for rpn

### ISSUE THREAD

**Issue by cr7legend** [amazon-research/siam-mot#9]
I was trying to improve upon this model for the AOT challenge organised by aicrowd. I am facing the issue of severe class imbalance  for rpn and box_head part.Even if posnegsampler is used which has pos ratio as 0.5, the implementation ends up with 1-2 positive labels out of the total 256 sampled anchors.These anchors also have extremely low IOU of 0.3-0.4 .How has this issue been been addressed in the  baseline for aot challenge?

**Comment by bingshuai2019** [comment]
The reason that the proposals are very extremely imbalanced is because of the fact: 1) very few objects are present in a frame and 2) the size of object is too small so the likelihood that an anchor highly overlaps with such small objects is very low (less positive proposals).

We didn't address this issue in the baseline tracker, which means that the current baseline tracker has room for improvement if you think this is a key issue for training.
